### ISSUE TITLE
Finish IMAP check

### ISSUE THREAD

**Issue by teknogeek** [nmpiazza/Hermes#4]
The IMAP service check is incomplete and needs to be finished. Currently, it will log in and fetch mailboxes, but it needs to do something after login to verify the service is working. Perhaps keep an email in a special inbox for the scoring engine to use and compare the hash of the contents of the email.

**Comment by teknogeek** [comment]
Not sure if using a separate mailbox to be checked by the scoring engine is the best route. Might be difficult since the for every team in a competition the mailbox would need to be set up, an email would have to be sent, and then that email would have to be moved into the right mailbox.

**Comment by teknogeek** [comment]
I've tested the code with it set up both ways. Maybe I will have the check look for it in the inbox if there is a `Scoring` mailbox. If there is, read the scoring email from that mailbox. If not, check if the scoring email is in the inbox. If it is, make a new mailbox called `Scoring` and move the email into it. Then, it will only check there from then on.

**Comment by nmpiazza** [comment]
Looks like you're using inconsistent logging in these lines. I think that you should be using `logger` instead of `logging` throughout. https://github.com/nmpiazza/Hermes/blob/70bd60b6552dbece988fd6cdda3cf7f614bd4691/app/mod_check/IMAP.py#L52-L60

**Comment by teknogeek** [comment]
Ahhhh whoops. Lemme fix that...
